"""
Django settings for news_platform project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env in the Django project root.
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    """
    Read a boolean environment variable using common truthy strings.
    """
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-54@xkec_ts_9oipgcfjdb3o=d!e6j7=1phgcn+**k+x45=58t&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  # Required to activate DRF.
    # Note: The HyperionDev M06T07 notes install DRF but do not mention
    # adding it here; cf. Antonio Melé, Django 5 By Example, p. 1124.
    # Also: https://members.codewithmosh.com/courses/the-ultimate-django-part2-1/lectures/34900117
    "rest_framework.authtoken",
    # Adds DRF's database-backed Token model plus the migrations/admin pieces
    # needed for token-based API authentication.
    # Cf.: https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
    # Project apps
    "accounts",
    "daily_indaba",
]

# Use the project's custom user model instead of Django's default User.
# Must be set before the first migration when using a custom user model.
# Cf.: https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = "accounts.User"  # Cf. Mele (2025:83)
# (It points to auth.User by default, but lets a project specify a different
#  user model. Here the custom model distinguishes readers, journalists, and
#  editors via the ``role`` field while still inheriting from AbstractUser.)


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "news_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Developer's note:
                # -------------------
                # "A context processor is a Python function that takes the
                # request object as an argument and returns a dictionary that
                # gets added to the request context. Context processors come
                # in handy when you need to make something available globally
                # to all templates." (Melé, 2025: 668). Kindle Edition.

                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # "django.template.context_processors.media",  <--- not used

                # Two approaches exist for resolving uploaded-file URLs in
                # templates (see Web Development with Django 6, Packt,
                # pp. 516-523):
                #
                # 1. Context-processor approach (Guest et al.): add
                #    "django.template.context_processors.media" here.  This
                #    injects MEDIA_URL as a bare string variable into every
                #    render context, so templates can construct paths manually:
                #        <img src="{{ MEDIA_URL }}{{ article.image }}">
                #    No model field is required — any string path works.
                #
                # 2. FieldFile .url approach (this project): omit the context
                #    processor and instead access the URL through Django's
                #    FieldFile descriptor on an ImageField / FileField.  Django
                #    prepends MEDIA_URL automatically, so templates use:
                #        <img src="{{ article.image.url }}">
                #    This requires the value to be a proper model FileField /
                #    ImageField — bare string paths have no .url attribute.
                #
                # Because every uploaded-file reference in this project goes
                # through a model field (article.image, profile_picture, etc.),
                # the context processor is intentionally omitted.
            ],
        },
    },
]

WSGI_APPLICATION = "news_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "news_platform"),
        "USER": os.getenv("DB_USER", "news_platform_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Guest et al. distinguish uploaded "media files" from static assets and
# recommend configuring MEDIA_ROOT / MEDIA_URL so user-uploaded images and
# documents live under a separate media directory.  This project uses that
# standard arrangement for profile pictures & article images.
# See Web Development with Django 6, Packt, pp. 509-516.
# Cf.: https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
# LOGIN_URL is where @login_required redirects unauthenticated users.
# LOGIN_REDIRECT_URL is the fallback after login when no 'next' param is
# present.
# LOGOUT_REDIRECT_URL is left as None so Django's built-in LogoutView renders
# the logged-out confirmation template instead of redirecting immediately.
# PASSWORD_RESET_TIMEOUT sets the lifetime of Django's built-in reset tokens.
# Cf.: https://docs.djangoproject.com/en/5.2/ref/settings/#login-url
#      Antonio Melé, Django 5 By Example, p. 349.
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "news:home"
LOGOUT_REDIRECT_URL = None
PASSWORD_RESET_TIMEOUT = 60 * 60

# Django REST Framework (DRF) configuration.
# TokenAuthentication — clients send 'Authorization: Token <key>' on every request.
# DRF tokens stay valid until they are deleted, so a normal Django web logout
# only ends the browser session; it does not revoke API tokens automatically.
# TokenLogoutView (daily_indaba/api_views.py) addresses this by calling
# `request.user.auth_token.delete()` on POST to /api/token/logout/.
# As per feedback to HyperionDev Task 14 (Django - eCommerce Application
# Part 2): the M06T07 submission's logout_user only called logout(request),
# leaving DRF tokens active after session end.
# Cf.: https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
#      https://dev.to/ebereplenty/how-to-log-users-out-in-django-rest-framework-drf-25ih
# IsAuthenticated     — every endpoint rejects unauthenticated requests with
#                       HTTP 401 unless the view sets
#                                             permission_classes = [AllowAny].
# JSONRenderer        — return JSON only; no browsable HTML API.
#                       DRF can also render HTML forms for browser interaction,
#                       but that requires HTML-capable renderers such as the
#                       Browsable API renderer instead of JSON-only output.
# Cf.: https://www.django-rest-framework.org/topics/html-and-forms/#rendering-html
# Cf.: https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# ----------------------------------------------------------------------
# Email settings
# ----------------------------------------------------------------------
# Email backend for development — prints emails to the console instead of
# delivering them via SMTP.  Switch to smtp.EmailBackend in production.
# EMAIL_FALLBACK_ENABLED / EMAIL_FALLBACK_BACKEND are custom settings used
# by accounts/utils.py so every project email flow can fall back to a second
# backend when the primary backend is unavailable.
# Cf.: https://docs.djangoproject.com/en/5.2/topics/email/#email-backends
EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_FALLBACK_ENABLED = env_bool("DJANGO_EMAIL_FALLBACK_ENABLED", DEBUG)
EMAIL_FALLBACK_BACKEND = (
    os.getenv(
        "DJANGO_EMAIL_FALLBACK_BACKEND",
        "django.core.mail.backends.console.EmailBackend" if DEBUG else "",
    )
)
EMAIL_HOST = os.getenv("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("DJANGO_EMAIL_PORT", "1025"))
EMAIL_HOST_USER = os.getenv("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("DJANGO_EMAIL_USE_TLS", False)
EMAIL_USE_SSL = env_bool("DJANGO_EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = int(os.getenv("DJANGO_EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = "noreply@thedailyindaba.co.za"
SITE_BASE_URL = "http://localhost:8000"

ANNOUNCEMENT_ENDPOINT = os.getenv(
    "DJANGO_ANNOUNCEMENT_ENDPOINT",
    f"{SITE_BASE_URL.rstrip('/')}/api/mock-announcements/",
)
ANNOUNCEMENT_TIMEOUT = int(os.getenv("DJANGO_ANNOUNCEMENT_TIMEOUT", "5"))
