# Generated by Django 5.2.4 on 2026-04-03 05:43

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "editorial categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting approval"),
                            ("returned", "Returned to journalist"),
                            ("approved", "Published"),
                        ],
                        default="pending",
                        help_text="Editorial workflow status. Pending articles are in the approval queue, returned articles are back with the journalist for revision, and approved articles are published.",
                        max_length=20,
                    ),
                ),
                (
                    "editor_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Optional editor feedback shown to the journalist when this article is returned for revision.",
                    ),
                ),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Front Page"), (2, "Top Story"), (3, "Standard")],
                        default=3,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Required for Front Page articles; optional for Top Story and Standard articles.",
                        null=True,
                        upload_to="articles/images/",
                    ),
                ),
                (
                    "disclaimer",
                    models.TextField(
                        blank=True,
                        help_text="Bias disclaimer added by the journalist or editor when potential bias is recognised in the article.",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The editor who approved this article for publication.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Editorial category assigned to this article.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="daily_indaba.newslettercategory",
                    ),
                ),
            ],
            options={
                "ordering": ["importance", "-publication_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(default=1)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="daily_indaba.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="daily_indaba.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="newsletters",
                        to="daily_indaba.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to="daily_indaba.newslettercategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curates_independent_journalists",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, editors affiliated with this publisher may review and approve independent articles that do not belong to a publisher.",
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=accounts.models.get_default_publisher_monthly_fee,
                        help_text="Monthly subscription fee (ZAR) charged to readers who subscribe to this publisher. The valid range is defined by the subscription pricing policy seed data. Set by an affiliated editor.",
                        max_digits=6,
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional publisher-role account that manages this publisher via self-service.",
                        limit_choices_to={"role": "publisher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_publisher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "editor"},
                        related_name="editor_publishers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journalists",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "journalist"},
                        related_name="journalist_publishers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="The publisher this article belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="daily_indaba.publisher",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journalist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journalist_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="daily_indaba.publisher",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("publisher__isnull", False),
                                ("journalist__isnull", True),
                            ),
                            models.Q(
                                ("publisher__isnull", True),
                                ("journalist__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="subscription_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        fields=("reader", "publisher"),
                        name="unique_reader_publisher_subscription",
                    ),
                    models.UniqueConstraint(
                        fields=("reader", "journalist"),
                        name="unique_reader_journalist_subscription",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="daily_indaba.article",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "recipient"),
                        name="unique_article_notification_per_recipient",
                    )
                ],
            },
        ),
    ]
